services:
  mongo_db:
    image: mongo:5.0.2
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
    ports:
      - $MONGODB_PORT:$MONGODB_PORT
    volumes:
      - db:/data/db

  app:
    depends_on:
      - mongo_db
    build: .
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $SPRING_PORT:$SPRING_PORT
    environment:
      SPRING_APPLICATION_JSON: '{
          "spring.data.mongodb.uri" : "mongodb://${MONGODB_USER}:${MONGODB_PASSWORD}@mongo_db:${MONGODB_PORT}/${MONGODB_DATABASE}?authSource=admin"
        }'
    volumes:
      - ~/.gradle:/home/gradle/.gradle
    stdin_open: true
    tty: true

volumes:
  db: