services:
  mongo_db:
    image: mongo:5.0.2
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=123456
    ports:
      - "27017:27017"
    volumes:
      - db:/data/db

  app:
    depends_on:
      - mongo_db
    build: .
    restart: unless-stopped
    env_file: ./.env
    ports:
      - "8088:8088"
    environment:
      SPRING_APPLICATION_JSON: '{
          "spring.data.mongodb.uri" : "mongodb://root:123456@mongo_db:27017/binance?authSource=admin"
        }'
    volumes:
      - ~/.gradle:/home/gradle/.gradle
    stdin_open: true
    tty: true

volumes:
  db: